# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/11PJRMORJVufYajCD8k1H_OCIHsdm18tV
"""

quantidade = 0
soma = 0.0
maiores_que_20 = 0
print("Digite os valores reais. Digite 'fim' para calcular os resultados.")
while True:
    entrada = input("Digite um valor: ")
    if entrada == 'fim':
        break
    try:
        valor = float(entrada)
        quantidade += 1
        soma += valor
        if valor > 20:
            maiores_que_20 += 1
    except ValueError:
        print("Atenção: Digite apenas números ou 'fim' para encerrar.")
media = soma / quantidade

print("--- RESULTADOS ---")
print("1. Quantidade de valores digitados:", quantidade)
print("2. Soma dos valores digitados:" , soma)
print("3. Média aritmética:", media)
print("4. Valores maiores que 20: ",maiores_que_20)

# Inicializamos o 'menor' com um valor gigante e o 'maior' com um valor muito pequeno.
menor = 99999999
maior = -99999999

while True:
    num = int(input("Digite um numero (0 para sair): "))

    if num == 0:
        break

    # Se o número digitado for MAIOR que o 'maior' atual, ele assume o posto
    if num > maior:
        maior = num

    # Se o número digitado for MENOR que o 'menor' atual, ele assume o posto
    if num < menor:
        menor = num

# Verificação de segurança: só imprime se algum número válido (diferente de 0) foi digitado
if maior != -99999999:
    print("Maior numero:", maior)
    print("Menor numero:", menor)
else:
    print("Nenhum número válido foi digitado.")

if number is str:
  print("invalid input")
number=int(input("digite um numero"))
number=int(input("digite um numero"))
number=int(input("digite um numero"))
number=int(input("digite um numero"))
number=int(input("digite um numero"))

x=None
for x in [number]:
   if x is None:
        x=number
   elif x<number:
        x=number
y=0
for y in [number]:
  if y>number:
    y=number
print("Maximum is",x)
print("Minimum is",y)

def area(largura,altura):
  area=largura*altura
  return area
sala=area(8,2)
print(sala)
casa=area(50,2)
print("a area total é:" ,casa)

while True:
  log=(input("oi"))
  if log==("ola"):
    break
  print("oi")

x=None
for  y in [1,2,3,4,71,7,-4]:
  if x is None:
   x=y
  elif y<x:
    x=y
print("menor numero é :",x)

for numero in range(33,0,-2):

 print(numero)

x=False
for valor in [9,41,12,3,74,15]:
  if valor==3:
    x=True
    break
print(x,valor)

numero=int(input("digite um numero"))
while True:
  numero2=int(input("digite um numero"))
  if numero==numero2:
    break
  if numero<numero2:
       print("numero muito alto")
       continue
  if numero>numero2:
       print("numero muito baixo")
       continue
print("acertou")

while True:
  talvez=(input("ola tudo bem como voce esta"))
  if talvez==("oi estou bem e voce"):
    break

print("que bom que voce esta bem ")

while True:
   ola=input("ola tudo bem")
   if ola==("oi"):
     continue
     print("que bom que voce esta bem")
   if ola==("oii"):
      break

def computepay(h, r):
   computepay=h*r
   return computepay
p = computepay(40,10.50)
horas_extras=float(input("quantidade de horas extras"))
y=((10.50*1.5)/100) # Changed 1,5 to 1.5
x=(y*horas_extras)
print("Pay", (p +x))

salario=int(input("salario?"))
despesas=int(input("despesas?"))
renda=salario-despesas#subtracao
print(("renda"),renda)
x=(10000/renda)
print(("x:"),x)

maior=99999999
menor=-9999999
while True:
  num=int(input("digitr "))
  if num==0:
    break
  if num>maior:
    maior=num
  if num<menor:
    menor=num
print("maior numero:",maior)
print("menor numero:",menor)

c=0
while True:
  num=int(input("qual o seu numero?"))
  if num==0:
    break
  if num > 2:
    c=c+1
print(("quantidade de numeros maiores que 2:"),c)

nota1=(float(input("nota da primeira prova?")))
nota2=(float(input("nota da segunda prova?")))
trabalho=(float(input("nota do trbalho?")))
print(("media:"),((nota1+nota2+trabalho)/3))
print(("media ponderada"),(nota1*2+nota2*2+trabalho)/5)

52
idade=int(input("qual a sua idade?"))
convite=str(input("possui convite?"))
if idade>18 and convite=="sim":
   print("entrada liberada")
elif idade<18 and (convite=="sim" or convite=="no"):
   print("entrada negada")
else:
   print("Condição não atendida para entrada liberada ou negada.")

numero=float(input("numero?"))
print(("dobro"),(numero*2))
print(("triplo"),(numero*3))
print(("quadrado do numero"),(numero**2))
print(("metade"),(numero/2))

salario=float(input("qual o seu salario?"))
parcela=float(input("qual o valor da parcela desejada"))
if parcela< (salario/3):
  print("parcela aceita")
elif parcela>(salario/3):
  print("parcela negada")
elif parcela==((salaraio*30)/100):
  print("sem limite permitido")

nota=int(input("qual a sua nota?"))
if nota>10:
  print("nota invalida")
elif nota>=9:
  print("aprovado com excelencia")
elif nota>10:
  print("nota invalida")
elif nota>=7:
  print("aprovado")
elif nota>=5 and nota<7:
   print("recuperacao")
else:
  print("reprovado!")

valor = int(input("qual o valor do saque?"))

notas_50 = valor // 50
resto = valor % 50

notas_20 = resto // 20
resto = resto % 20

notas_10 = resto // 10
resto = resto % 10

notas_5 = resto // 5
resto = resto % 5

notas_1 = resto // 1

print("Notas a serem entregues:")
if notas_50 > 0:
  print(f"Notas de 50: {notas_50}")
if notas_20 > 0:
  print(f"Notas de 20: {notas_20}")
if notas_10 > 0:
  print(f"Notas de 10: {notas_10}")
if notas_5 > 0:
  print(f"Notas de 5: {notas_5}")
if notas_1 > 0:
  print(f"Notas de 1: {notas_1}")

nota=int(input("numero de 0 a 10"))
if nota>=9:
  print("aprovado com excelencia")
elif nota>=7:
  print("aprovado")
elif nota>=5 and nota<7:
  print("recuperacao")
elif nota<5:
  print("reprovado")

idade=int(input("qual a sua idade"))
convite=str(input("possui convite?"))
if idade>18 and convite=="sim":
  print("entrada liberada")
else :
  print("entrada negada")

x=0
while x<20:
  print(x)
  x=x+2

ct=0
homem=0
mulher=0
while True:
  sexo=str(input("qual o seu sexo?"))
  if sexo=="fim":
    break
  if sexo=="m":
    homem=homem+1
  if sexo=="f":
    mulher=mulher+1
  ct=ct+1
print("total de pessoas:",ct)
print("homens:",homem)
print("mulheres:",mulher)

x=10
print(x)
print(id(x))

ola=0
soma=0
while True:
  num=int(input("digite um numero"))
  if num==0:
    break
  if num>1:
    ola=ola+1
    soma=soma+num
print("quantidade de numeros maiores que 1:",ola)
print("soma dos numeros:",soma)

lista1=[1,2,3]
lista2=[3,4,5]
print(lista1+lista2)

nota2=int(input("qual a sua nota?"))
nota1=int(input("qual a sua nota?"))
lista=[9,8,7,6,5,4,]
if nota1 and nota2 in lista:
  print("aprovado")
elif nota1 and nota2 <5:
  print("recuperacao")
else :
    print("reprovado")
print(f'sua nota é: {nota}')
print(f' sua media é: {(nota1 +nota2)/2}')
